// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package io.scyna.ex.account.proto;

public interface CreateAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.scyna.customer.proto.CreateAccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
