// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package io.scyna.ex.account.proto;

public interface GetAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.scyna.customer.proto.GetAccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ID = 1;</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <code>string ID = 1;</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();

  /**
   * <code>string Name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string Name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string Email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
