// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package io.scyna.ex.account.proto;

/**
 * Protobuf type {@code io.scyna.customer.proto.PasswordChanged}
 */
public final class PasswordChanged extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.scyna.customer.proto.PasswordChanged)
    PasswordChangedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PasswordChanged.newBuilder() to construct.
  private PasswordChanged(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PasswordChanged() {
    current_ = "";
    future_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PasswordChanged();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PasswordChanged(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            current_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            future_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.scyna.ex.account.proto.Account.internal_static_io_scyna_customer_proto_PasswordChanged_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.scyna.ex.account.proto.Account.internal_static_io_scyna_customer_proto_PasswordChanged_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.scyna.ex.account.proto.PasswordChanged.class, io.scyna.ex.account.proto.PasswordChanged.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int CURRENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object current_;
  /**
   * <code>string current = 2;</code>
   * @return The current.
   */
  @java.lang.Override
  public java.lang.String getCurrent() {
    java.lang.Object ref = current_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      current_ = s;
      return s;
    }
  }
  /**
   * <code>string current = 2;</code>
   * @return The bytes for current.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentBytes() {
    java.lang.Object ref = current_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      current_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUTURE_FIELD_NUMBER = 3;
  private volatile java.lang.Object future_;
  /**
   * <code>string future = 3;</code>
   * @return The future.
   */
  @java.lang.Override
  public java.lang.String getFuture() {
    java.lang.Object ref = future_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      future_ = s;
      return s;
    }
  }
  /**
   * <code>string future = 3;</code>
   * @return The bytes for future.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFutureBytes() {
    java.lang.Object ref = future_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      future_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeUInt64(1, id_);
    }
    if (!getCurrentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, current_);
    }
    if (!getFutureBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, future_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (!getCurrentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, current_);
    }
    if (!getFutureBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, future_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.scyna.ex.account.proto.PasswordChanged)) {
      return super.equals(obj);
    }
    io.scyna.ex.account.proto.PasswordChanged other = (io.scyna.ex.account.proto.PasswordChanged) obj;

    if (getId()
        != other.getId()) return false;
    if (!getCurrent()
        .equals(other.getCurrent())) return false;
    if (!getFuture()
        .equals(other.getFuture())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CURRENT_FIELD_NUMBER;
    hash = (53 * hash) + getCurrent().hashCode();
    hash = (37 * hash) + FUTURE_FIELD_NUMBER;
    hash = (53 * hash) + getFuture().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.scyna.ex.account.proto.PasswordChanged parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.scyna.ex.account.proto.PasswordChanged prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.scyna.customer.proto.PasswordChanged}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.scyna.customer.proto.PasswordChanged)
      io.scyna.ex.account.proto.PasswordChangedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.scyna.ex.account.proto.Account.internal_static_io_scyna_customer_proto_PasswordChanged_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.scyna.ex.account.proto.Account.internal_static_io_scyna_customer_proto_PasswordChanged_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.scyna.ex.account.proto.PasswordChanged.class, io.scyna.ex.account.proto.PasswordChanged.Builder.class);
    }

    // Construct using io.scyna.ex.account.proto.PasswordChanged.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      current_ = "";

      future_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.scyna.ex.account.proto.Account.internal_static_io_scyna_customer_proto_PasswordChanged_descriptor;
    }

    @java.lang.Override
    public io.scyna.ex.account.proto.PasswordChanged getDefaultInstanceForType() {
      return io.scyna.ex.account.proto.PasswordChanged.getDefaultInstance();
    }

    @java.lang.Override
    public io.scyna.ex.account.proto.PasswordChanged build() {
      io.scyna.ex.account.proto.PasswordChanged result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.scyna.ex.account.proto.PasswordChanged buildPartial() {
      io.scyna.ex.account.proto.PasswordChanged result = new io.scyna.ex.account.proto.PasswordChanged(this);
      result.id_ = id_;
      result.current_ = current_;
      result.future_ = future_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.scyna.ex.account.proto.PasswordChanged) {
        return mergeFrom((io.scyna.ex.account.proto.PasswordChanged)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.scyna.ex.account.proto.PasswordChanged other) {
      if (other == io.scyna.ex.account.proto.PasswordChanged.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getCurrent().isEmpty()) {
        current_ = other.current_;
        onChanged();
      }
      if (!other.getFuture().isEmpty()) {
        future_ = other.future_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.scyna.ex.account.proto.PasswordChanged parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.scyna.ex.account.proto.PasswordChanged) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object current_ = "";
    /**
     * <code>string current = 2;</code>
     * @return The current.
     */
    public java.lang.String getCurrent() {
      java.lang.Object ref = current_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        current_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string current = 2;</code>
     * @return The bytes for current.
     */
    public com.google.protobuf.ByteString
        getCurrentBytes() {
      java.lang.Object ref = current_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        current_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string current = 2;</code>
     * @param value The current to set.
     * @return This builder for chaining.
     */
    public Builder setCurrent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      current_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string current = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrent() {
      
      current_ = getDefaultInstance().getCurrent();
      onChanged();
      return this;
    }
    /**
     * <code>string current = 2;</code>
     * @param value The bytes for current to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      current_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object future_ = "";
    /**
     * <code>string future = 3;</code>
     * @return The future.
     */
    public java.lang.String getFuture() {
      java.lang.Object ref = future_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        future_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string future = 3;</code>
     * @return The bytes for future.
     */
    public com.google.protobuf.ByteString
        getFutureBytes() {
      java.lang.Object ref = future_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        future_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string future = 3;</code>
     * @param value The future to set.
     * @return This builder for chaining.
     */
    public Builder setFuture(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      future_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string future = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFuture() {
      
      future_ = getDefaultInstance().getFuture();
      onChanged();
      return this;
    }
    /**
     * <code>string future = 3;</code>
     * @param value The bytes for future to set.
     * @return This builder for chaining.
     */
    public Builder setFutureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      future_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.scyna.customer.proto.PasswordChanged)
  }

  // @@protoc_insertion_point(class_scope:io.scyna.customer.proto.PasswordChanged)
  private static final io.scyna.ex.account.proto.PasswordChanged DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.scyna.ex.account.proto.PasswordChanged();
  }

  public static io.scyna.ex.account.proto.PasswordChanged getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PasswordChanged>
      PARSER = new com.google.protobuf.AbstractParser<PasswordChanged>() {
    @java.lang.Override
    public PasswordChanged parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PasswordChanged(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PasswordChanged> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PasswordChanged> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.scyna.ex.account.proto.PasswordChanged getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

