// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registering.proto

package ex.registering.proto;

public interface OtpGeneratedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OtpGenerated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string Email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string Otp = 2;</code>
   */
  java.lang.String getOtp();
  /**
   * <code>string Otp = 2;</code>
   */
  com.google.protobuf.ByteString
      getOtpBytes();
}
