// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registering.proto

package ex.registering.proto;

public interface RegistrationDeletedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationDeleted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string Email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string Name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
