// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adapter-send-email.proto

package ex.registering.proto;

public interface SendEmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendEmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string Email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string Content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string Content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
