// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: creating.proto

package ex.account.proto;

public final class Creating {
  private Creating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountCreated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016creating.proto\"E\n\024CreateAccountRequest" +
      "\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\r\n\005emai" +
      "l\030\004 \001(\t\"K\n\016AccountCreated\022\n\n\002id\030\001 \001(\004\022\014\n" +
      "\004name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\r\n\005email\030\004" +
      " \001(\tB\'\n\020ex.account.protoP\001\252\002\020ex.account." +
      "PROTOb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateAccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAccountRequest_descriptor,
        new java.lang.String[] { "Name", "Password", "Email", });
    internal_static_AccountCreated_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AccountCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountCreated_descriptor,
        new java.lang.String[] { "Id", "Name", "Password", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
