// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package scyna.ex.customer.proto;

public interface GetCustomerResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.scyna.customer.proto.GetCustomerResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ID = 1;</code>
     * 
     * @return The iD.
     */
    java.lang.String getID();

    /**
     * <code>string ID = 1;</code>
     * 
     * @return The bytes for iD.
     */
    com.google.protobuf.ByteString getIDBytes();

    /**
     * <code>string Name = 2;</code>
     * 
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string Name = 2;</code>
     * 
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>string IDType = 3;</code>
     * 
     * @return The iDType.
     */
    java.lang.String getIDType();

    /**
     * <code>string IDType = 3;</code>
     * 
     * @return The bytes for iDType.
     */
    com.google.protobuf.ByteString getIDTypeBytes();

    /**
     * <code>string IDNumber = 4;</code>
     * 
     * @return The iDNumber.
     */
    java.lang.String getIDNumber();

    /**
     * <code>string IDNumber = 4;</code>
     * 
     * @return The bytes for iDNumber.
     */
    com.google.protobuf.ByteString getIDNumberBytes();
}
