// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: API.proto

package io.scyna.ex.basic.proto;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();
}
