// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine.proto

package io.scyna.proto;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Organization = 1;</code>
   * @return The organization.
   */
  java.lang.String getOrganization();
  /**
   * <code>string Organization = 1;</code>
   * @return The bytes for organization.
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();

  /**
   * <code>string Secret = 2;</code>
   * @return The secret.
   */
  java.lang.String getSecret();
  /**
   * <code>string Secret = 2;</code>
   * @return The bytes for secret.
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <code>string UserID = 3;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string UserID = 3;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string Token = 4;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string Token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
