// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package scyna.ex.account.proto;

public interface CreateAccountRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.scyna.customer.proto.CreateAccountRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string email = 1;</code>
     * 
     * @return The email.
     */
    java.lang.String getEmail();

    /**
     * <code>string email = 1;</code>
     * 
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString getEmailBytes();

    /**
     * <code>string name = 2;</code>
     * 
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 2;</code>
     * 
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>string password = 3;</code>
     * 
     * @return The password.
     */
    java.lang.String getPassword();

    /**
     * <code>string password = 3;</code>
     * 
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString getPasswordBytes();
}
