// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager.proto

package io.scyna.proto;

public interface AuthenticationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.velo.proto.AuthenticationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 SessionID = 1;</code>
   * @return The sessionID.
   */
  long getSessionID();

  /**
   * <code>.io.velo.proto.Configuration Config = 5;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.io.velo.proto.Configuration Config = 5;</code>
   * @return The config.
   */
  io.scyna.proto.Configuration getConfig();
  /**
   * <code>.io.velo.proto.Configuration Config = 5;</code>
   */
  io.scyna.proto.ConfigurationOrBuilder getConfigOrBuilder();
}
