// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine.proto

package io.scyna.proto;

/**
 * Protobuf type {@code io.scyna.proto.CreateSessionResponse}
 */
public final class CreateSessionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.scyna.proto.CreateSessionResponse)
    CreateSessionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateSessionResponse.newBuilder() to construct.
  private CreateSessionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateSessionResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateSessionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.scyna.proto.Engine.internal_static_io_scyna_proto_CreateSessionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.scyna.proto.Engine.internal_static_io_scyna_proto_CreateSessionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.scyna.proto.CreateSessionResponse.class, io.scyna.proto.CreateSessionResponse.Builder.class);
  }

  public static final int SESSIONID_FIELD_NUMBER = 1;
  private long sessionID_;
  /**
   * <code>uint64 SessionID = 1;</code>
   * @return The sessionID.
   */
  @java.lang.Override
  public long getSessionID() {
    return sessionID_;
  }

  public static final int CONFIG_FIELD_NUMBER = 5;
  private io.scyna.proto.Configuration config_;
  /**
   * <code>.io.scyna.proto.Configuration Config = 5;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return config_ != null;
  }
  /**
   * <code>.io.scyna.proto.Configuration Config = 5;</code>
   * @return The config.
   */
  @java.lang.Override
  public io.scyna.proto.Configuration getConfig() {
    return config_ == null ? io.scyna.proto.Configuration.getDefaultInstance() : config_;
  }
  /**
   * <code>.io.scyna.proto.Configuration Config = 5;</code>
   */
  @java.lang.Override
  public io.scyna.proto.ConfigurationOrBuilder getConfigOrBuilder() {
    return getConfig();
  }

  public static io.scyna.proto.CreateSessionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.scyna.proto.CreateSessionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.scyna.proto.CreateSessionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.scyna.proto.CreateSessionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.scyna.proto.CreateSessionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.scyna.proto.CreateSessionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.scyna.proto.CreateSessionResponse)
      io.scyna.proto.CreateSessionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.scyna.proto.Engine.internal_static_io_scyna_proto_CreateSessionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.scyna.proto.Engine.internal_static_io_scyna_proto_CreateSessionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.scyna.proto.CreateSessionResponse.class, io.scyna.proto.CreateSessionResponse.Builder.class);
    }

    // Construct using io.scyna.proto.CreateSessionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sessionID_ = 0L;

      if (configBuilder_ == null) {
        config_ = null;
      } else {
        config_ = null;
        configBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.scyna.proto.Engine.internal_static_io_scyna_proto_CreateSessionResponse_descriptor;
    }

    @java.lang.Override
    public io.scyna.proto.CreateSessionResponse getDefaultInstanceForType() {
      return io.scyna.proto.CreateSessionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.scyna.proto.CreateSessionResponse build() {
      io.scyna.proto.CreateSessionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.scyna.proto.CreateSessionResponse buildPartial() {
      io.scyna.proto.CreateSessionResponse result = new io.scyna.proto.CreateSessionResponse(this);
      result.sessionID_ = sessionID_;
      if (configBuilder_ == null) {
        result.config_ = config_;
      } else {
        result.config_ = configBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    private long sessionID_ ;
    /**
     * <code>uint64 SessionID = 1;</code>
     * @return The sessionID.
     */
    @java.lang.Override
    public long getSessionID() {
      return sessionID_;
    }
    /**
     * <code>uint64 SessionID = 1;</code>
     * @param value The sessionID to set.
     * @return This builder for chaining.
     */
    public Builder setSessionID(long value) {
      
      sessionID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 SessionID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionID() {
      
      sessionID_ = 0L;
      onChanged();
      return this;
    }

    private io.scyna.proto.Configuration config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.scyna.proto.Configuration, io.scyna.proto.Configuration.Builder, io.scyna.proto.ConfigurationOrBuilder> configBuilder_;
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return configBuilder_ != null || config_ != null;
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     * @return The config.
     */
    public io.scyna.proto.Configuration getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? io.scyna.proto.Configuration.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    public Builder setConfig(io.scyna.proto.Configuration value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        configBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    public Builder setConfig(
        io.scyna.proto.Configuration.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    public Builder mergeConfig(io.scyna.proto.Configuration value) {
      if (configBuilder_ == null) {
        if (config_ != null) {
          config_ =
            io.scyna.proto.Configuration.newBuilder(config_).mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        configBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        config_ = null;
        onChanged();
      } else {
        config_ = null;
        configBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    public io.scyna.proto.Configuration.Builder getConfigBuilder() {
      
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    public io.scyna.proto.ConfigurationOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            io.scyna.proto.Configuration.getDefaultInstance() : config_;
      }
    }
    /**
     * <code>.io.scyna.proto.Configuration Config = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.scyna.proto.Configuration, io.scyna.proto.Configuration.Builder, io.scyna.proto.ConfigurationOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.scyna.proto.Configuration, io.scyna.proto.Configuration.Builder, io.scyna.proto.ConfigurationOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.scyna.proto.CreateSessionResponse)
  }

  // @@protoc_insertion_point(class_scope:io.scyna.proto.CreateSessionResponse)
  private static final io.scyna.proto.CreateSessionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.scyna.proto.CreateSessionResponse();
  }

  public static io.scyna.proto.CreateSessionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSessionResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateSessionResponse>() {
    @java.lang.Override
    public CreateSessionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateSessionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSessionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.scyna.proto.CreateSessionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

