// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine.proto

package io.scyna.proto;

public interface CreateSessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.scyna.proto.CreateSessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 SessionID = 1;</code>
   * @return The sessionID.
   */
  long getSessionID();

  /**
   * <code>.io.scyna.proto.Configuration Config = 5;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.io.scyna.proto.Configuration Config = 5;</code>
   * @return The config.
   */
  io.scyna.proto.Configuration getConfig();
  /**
   * <code>.io.scyna.proto.Configuration Config = 5;</code>
   */
  io.scyna.proto.ConfigurationOrBuilder getConfigOrBuilder();
}
