// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package io.scyna.proto;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.scyna.proto.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 Code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string Message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string Message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
