// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scyna.proto

package io.scyna.proto;

public interface EventOrSignalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.EventOrSignal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 CallID = 1;</code>
   * @return The callID.
   */
  long getCallID();

  /**
   * <code>bytes Body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>string Data = 3;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string Data = 3;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
