// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager.proto

package io.scyna.proto;

public interface GetIDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.velo.proto.GetIDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 prefix = 1;</code>
   * @return The prefix.
   */
  int getPrefix();

  /**
   * <code>uint64 start = 2;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>uint64 end = 3;</code>
   * @return The end.
   */
  long getEnd();
}
