// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scyna.proto

package io.scyna.proto;

public final class Scyna {
  private Scyna() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scyna_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scyna_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scyna_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scyna_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scyna_EventOrSignal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scyna_EventOrSignal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013scyna.proto\022\005scyna\"C\n\007Request\022\016\n\006CallI" +
      "D\030\001 \001(\004\022\014\n\004Body\030\002 \001(\014\022\014\n\004JSON\030\003 \001(\010\022\014\n\004D" +
      "ata\030\004 \001(\t\"Y\n\010Response\022\014\n\004Code\030\001 \001(\005\022\014\n\004B" +
      "ody\030\002 \001(\014\022\021\n\tSessionID\030\003 \001(\004\022\r\n\005Token\030\004 " +
      "\001(\t\022\017\n\007Expired\030\005 \001(\004\";\n\rEventOrSignal\022\016\n" +
      "\006CallID\030\001 \001(\004\022\014\n\004Body\030\002 \001(\014\022\014\n\004Data\030\003 \001(" +
      "\tB\035\n\016io.scyna.protoH\002P\001Z\007.;scynab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_scyna_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scyna_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scyna_Request_descriptor,
        new java.lang.String[] { "CallID", "Body", "JSON", "Data", });
    internal_static_scyna_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scyna_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scyna_Response_descriptor,
        new java.lang.String[] { "Code", "Body", "SessionID", "Token", "Expired", });
    internal_static_scyna_EventOrSignal_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_scyna_EventOrSignal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scyna_EventOrSignal_descriptor,
        new java.lang.String[] { "CallID", "Body", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
