// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine.proto

package scyna.proto;

public final class Engine {
    private Engine() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_Configuration_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_Configuration_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_CreateSessionRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_CreateSessionRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_CreateSessionResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_CreateSessionResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_EndSessionSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_EndSessionSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_UpdateSessionSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_UpdateSessionSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_GetIDRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_GetIDRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_GetIDResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_GetIDResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_GetSNRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_GetSNRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_GetSNResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_GetSNResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_LogCreatedSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_LogCreatedSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_TraceCreatedSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_TraceCreatedSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_TagCreatedSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_TagCreatedSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_EndpointDoneSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_EndpointDoneSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_WriteSettingRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_WriteSettingRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_ReadSettingRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_ReadSettingRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_ReadSettingResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_ReadSettingResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_SettingUpdatedSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_SettingUpdatedSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_SettingRemovedSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_SettingRemovedSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_RemoveSettingRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_RemoveSettingRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_WriteCallSignal_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_WriteCallSignal_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_CreateAuthRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_CreateAuthRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_CreateAuthResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_CreateAuthResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_GetAuthRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_GetAuthRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_GetAuthResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_GetAuthResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_scyna_LogoutRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_scyna_LogoutRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014engine.proto\022\005scyna\"\230\001\n\rConfiguration\022" +
                        "\017\n\007NatsUrl\030\001 \001(\t\022\024\n\014NatsUsername\030\002 \001(\t\022\024" +
                        "\n\014NatsPassword\030\003 \001(\t\022\016\n\006DBHost\030\004 \001(\t\022\022\n\n" +
                        "DBUsername\030\005 \001(\t\022\022\n\nDBPassword\030\006 \001(\t\022\022\n\n" +
                        "DBLocation\030\007 \001(\t\"6\n\024CreateSessionRequest" +
                        "\022\016\n\006Module\030\001 \001(\t\022\016\n\006Secret\030\002 \001(\t\"P\n\025Crea" +
                        "teSessionResponse\022\021\n\tSessionID\030\001 \001(\004\022$\n\006" +
                        "Config\030\005 \001(\0132\024.scyna.Configuration\"<\n\020En" +
                        "dSessionSignal\022\n\n\002ID\030\001 \001(\004\022\014\n\004Code\030\002 \001(\t" +
                        "\022\016\n\006Module\030\003 \001(\t\"1\n\023UpdateSessionSignal\022" +
                        "\n\n\002ID\030\001 \001(\004\022\016\n\006Module\030\002 \001(\t\"\016\n\014GetIDRequ" +
                        "est\";\n\rGetIDResponse\022\016\n\006prefix\030\001 \001(\r\022\r\n\005" +
                        "start\030\002 \001(\004\022\013\n\003end\030\003 \001(\004\"\033\n\014GetSNRequest" +
                        "\022\013\n\003key\030\001 \001(\t\";\n\rGetSNResponse\022\016\n\006prefix" +
                        "\030\001 \001(\r\022\r\n\005start\030\002 \001(\004\022\013\n\003end\030\003 \001(\004\"g\n\020Lo"
                        +
                        "gCreatedSignal\022\014\n\004Time\030\001 \001(\004\022\r\n\005Level\030\002 " +
                        "\001(\r\022\014\n\004Text\030\003 \001(\t\022\n\n\002ID\030\004 \001(\004\022\013\n\003SEQ\030\005 \001"
                        +
                        "(\004\022\017\n\007Session\030\006 \001(\010\"\241\001\n\022TraceCreatedSign" +
                        "al\022\n\n\002ID\030\001 \001(\004\022\020\n\010ParentID\030\002 \001(\004\022\014\n\004Type" +
                        "\030\003 \001(\r\022\014\n\004Time\030\004 \001(\004\022\020\n\010Duration\030\005 \001(\004\022\014"
                        +
                        "\n\004Path\030\006 \001(\t\022\016\n\006Source\030\007 \001(\t\022\021\n\tSessionI" +
                        "D\030\010 \001(\004\022\016\n\006Status\030\t \001(\005\"?\n\020TagCreatedSig" +
                        "nal\022\017\n\007TraceID\030\001 \001(\004\022\013\n\003Key\030\002 \001(\t\022\r\n\005Val" +
                        "ue\030\003 \001(\t\"7\n\022EndpointDoneSignal\022\017\n\007TraceI" +
                        "D\030\001 \001(\004\022\020\n\010Response\030\002 \001(\t\"A\n\023WriteSettin" +
                        "gRequest\022\016\n\006Module\030\001 \001(\t\022\013\n\003Key\030\002 \001(\t\022\r\n" +
                        "\005Value\030\003 \001(\t\"1\n\022ReadSettingRequest\022\016\n\006Mo" +
                        "dule\030\001 \001(\t\022\013\n\003Key\030\002 \001(\t\"$\n\023ReadSettingRe" +
                        "sponse\022\r\n\005Value\030\001 \001(\t\"B\n\024SettingUpdatedS" +
                        "ignal\022\016\n\006Module\030\001 \001(\t\022\013\n\003Key\030\002 \001(\t\022\r\n\005Va" +
                        "lue\030\003 \001(\t\"3\n\024SettingRemovedSignal\022\016\n\006Mod" +
                        "ule\030\001 \001(\t\022\013\n\003Key\030\002 \001(\t\"3\n\024RemoveSettingR" +
                        "equest\022\016\n\006Module\030\001 \001(\t\022\013\n\003Key\030\002 \001(\t\"\264\001\n\017" +
                        "WriteCallSignal\022\n\n\002id\030\001 \001(\004\022\016\n\006source\030\002 " +
                        "\001(\t\022\021\n\tcaller_id\030\003 \001(\t\022\022\n\nsession_id\030\004 \001" +
                        "(\004\022\020\n\010duration\030\005 \001(\r\022\017\n\007request\030\006 \001(\014\022\020\n" +
                        "\010response\030\007 \001(\014\022\016\n\006status\030\010 \001(\r\022\014\n\004time\030" +
                        "\t \001(\004\022\013\n\003day\030\n \001(\r\"W\n\021CreateAuthRequest\022" +
                        "\024\n\014Organization\030\001 \001(\t\022\016\n\006Secret\030\002 \001(\t\022\016\n" +
                        "\006UserID\030\003 \001(\t\022\014\n\004Apps\030\004 \003(\t\"4\n\022CreateAut" +
                        "hResponse\022\r\n\005Token\030\001 \001(\t\022\017\n\007Expired\030\002 \001(" +
                        "\004\",\n\016GetAuthRequest\022\r\n\005Token\030\001 \001(\t\022\013\n\003Ap" +
                        "p\030\002 \001(\t\"A\n\017GetAuthResponse\022\r\n\005Token\030\001 \001(" +
                        "\t\022\017\n\007Expired\030\002 \001(\004\022\016\n\006UserID\030\003 \001(\t\"T\n\rLo" +
                        "goutRequest\022\024\n\014Organization\030\001 \001(\t\022\016\n\006Sec" +
                        "ret\030\002 \001(\t\022\016\n\006UserID\030\003 \001(\t\022\r\n\005Token\030\004 \001(\t" +
                        "B2\n\016io.scyna.protoH\002P\001Z\016./;scyna_proto\252\002" +
                        "\013scyna.protob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_scyna_Configuration_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_scyna_Configuration_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_Configuration_descriptor,
                new java.lang.String[] { "NatsUrl", "NatsUsername", "NatsPassword", "DBHost", "DBUsername",
                        "DBPassword", "DBLocation", });
        internal_static_scyna_CreateSessionRequest_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_scyna_CreateSessionRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_CreateSessionRequest_descriptor,
                new java.lang.String[] { "Module", "Secret", });
        internal_static_scyna_CreateSessionResponse_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_scyna_CreateSessionResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_CreateSessionResponse_descriptor,
                new java.lang.String[] { "SessionID", "Config", });
        internal_static_scyna_EndSessionSignal_descriptor = getDescriptor().getMessageTypes().get(3);
        internal_static_scyna_EndSessionSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_EndSessionSignal_descriptor,
                new java.lang.String[] { "ID", "Code", "Module", });
        internal_static_scyna_UpdateSessionSignal_descriptor = getDescriptor().getMessageTypes().get(4);
        internal_static_scyna_UpdateSessionSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_UpdateSessionSignal_descriptor,
                new java.lang.String[] { "ID", "Module", });
        internal_static_scyna_GetIDRequest_descriptor = getDescriptor().getMessageTypes().get(5);
        internal_static_scyna_GetIDRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_GetIDRequest_descriptor,
                new java.lang.String[] {});
        internal_static_scyna_GetIDResponse_descriptor = getDescriptor().getMessageTypes().get(6);
        internal_static_scyna_GetIDResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_GetIDResponse_descriptor,
                new java.lang.String[] { "Prefix", "Start", "End", });
        internal_static_scyna_GetSNRequest_descriptor = getDescriptor().getMessageTypes().get(7);
        internal_static_scyna_GetSNRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_GetSNRequest_descriptor,
                new java.lang.String[] { "Key", });
        internal_static_scyna_GetSNResponse_descriptor = getDescriptor().getMessageTypes().get(8);
        internal_static_scyna_GetSNResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_GetSNResponse_descriptor,
                new java.lang.String[] { "Prefix", "Start", "End", });
        internal_static_scyna_LogCreatedSignal_descriptor = getDescriptor().getMessageTypes().get(9);
        internal_static_scyna_LogCreatedSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_LogCreatedSignal_descriptor,
                new java.lang.String[] { "Time", "Level", "Text", "ID", "SEQ", "Session", });
        internal_static_scyna_TraceCreatedSignal_descriptor = getDescriptor().getMessageTypes().get(10);
        internal_static_scyna_TraceCreatedSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_TraceCreatedSignal_descriptor,
                new java.lang.String[] { "ID", "ParentID", "Type", "Time", "Duration", "Path", "Source", "SessionID",
                        "Status", });
        internal_static_scyna_TagCreatedSignal_descriptor = getDescriptor().getMessageTypes().get(11);
        internal_static_scyna_TagCreatedSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_TagCreatedSignal_descriptor,
                new java.lang.String[] { "TraceID", "Key", "Value", });
        internal_static_scyna_EndpointDoneSignal_descriptor = getDescriptor().getMessageTypes().get(12);
        internal_static_scyna_EndpointDoneSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_EndpointDoneSignal_descriptor,
                new java.lang.String[] { "TraceID", "Response", });
        internal_static_scyna_WriteSettingRequest_descriptor = getDescriptor().getMessageTypes().get(13);
        internal_static_scyna_WriteSettingRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_WriteSettingRequest_descriptor,
                new java.lang.String[] { "Module", "Key", "Value", });
        internal_static_scyna_ReadSettingRequest_descriptor = getDescriptor().getMessageTypes().get(14);
        internal_static_scyna_ReadSettingRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_ReadSettingRequest_descriptor,
                new java.lang.String[] { "Module", "Key", });
        internal_static_scyna_ReadSettingResponse_descriptor = getDescriptor().getMessageTypes().get(15);
        internal_static_scyna_ReadSettingResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_ReadSettingResponse_descriptor,
                new java.lang.String[] { "Value", });
        internal_static_scyna_SettingUpdatedSignal_descriptor = getDescriptor().getMessageTypes().get(16);
        internal_static_scyna_SettingUpdatedSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_SettingUpdatedSignal_descriptor,
                new java.lang.String[] { "Module", "Key", "Value", });
        internal_static_scyna_SettingRemovedSignal_descriptor = getDescriptor().getMessageTypes().get(17);
        internal_static_scyna_SettingRemovedSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_SettingRemovedSignal_descriptor,
                new java.lang.String[] { "Module", "Key", });
        internal_static_scyna_RemoveSettingRequest_descriptor = getDescriptor().getMessageTypes().get(18);
        internal_static_scyna_RemoveSettingRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_RemoveSettingRequest_descriptor,
                new java.lang.String[] { "Module", "Key", });
        internal_static_scyna_WriteCallSignal_descriptor = getDescriptor().getMessageTypes().get(19);
        internal_static_scyna_WriteCallSignal_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_WriteCallSignal_descriptor,
                new java.lang.String[] { "Id", "Source", "CallerId", "SessionId", "Duration", "Request", "Response",
                        "Status", "Time", "Day", });
        internal_static_scyna_CreateAuthRequest_descriptor = getDescriptor().getMessageTypes().get(20);
        internal_static_scyna_CreateAuthRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_CreateAuthRequest_descriptor,
                new java.lang.String[] { "Organization", "Secret", "UserID", "Apps", });
        internal_static_scyna_CreateAuthResponse_descriptor = getDescriptor().getMessageTypes().get(21);
        internal_static_scyna_CreateAuthResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_CreateAuthResponse_descriptor,
                new java.lang.String[] { "Token", "Expired", });
        internal_static_scyna_GetAuthRequest_descriptor = getDescriptor().getMessageTypes().get(22);
        internal_static_scyna_GetAuthRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_GetAuthRequest_descriptor,
                new java.lang.String[] { "Token", "App", });
        internal_static_scyna_GetAuthResponse_descriptor = getDescriptor().getMessageTypes().get(23);
        internal_static_scyna_GetAuthResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_GetAuthResponse_descriptor,
                new java.lang.String[] { "Token", "Expired", "UserID", });
        internal_static_scyna_LogoutRequest_descriptor = getDescriptor().getMessageTypes().get(24);
        internal_static_scyna_LogoutRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scyna_LogoutRequest_descriptor,
                new java.lang.String[] { "Organization", "Secret", "UserID", "Token", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
