// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: id.proto

package scyna.proto;

public interface GetSNResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.GetSNResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 prefix = 1;</code>
   */
  int getPrefix();

  /**
   * <code>uint64 start = 2;</code>
   */
  long getStart();

  /**
   * <code>uint64 end = 3;</code>
   */
  long getEnd();
}
