// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scyna.proto

package scyna.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 Code = 1;</code>
   */
  int getCode();

  /**
   * <code>bytes Body = 2;</code>
   */
  com.google.protobuf.ByteString getBody();
}
