// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine.proto

package scyna.proto;

public interface SettingUpdatedSignalOrBuilder extends
        // @@protoc_insertion_point(interface_extends:scyna.SettingUpdatedSignal)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Module = 1;</code>
     * 
     * @return The module.
     */
    java.lang.String getModule();

    /**
     * <code>string Module = 1;</code>
     * 
     * @return The bytes for module.
     */
    com.google.protobuf.ByteString getModuleBytes();

    /**
     * <code>string Key = 2;</code>
     * 
     * @return The key.
     */
    java.lang.String getKey();

    /**
     * <code>string Key = 2;</code>
     * 
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString getKeyBytes();

    /**
     * <code>string Value = 3;</code>
     * 
     * @return The value.
     */
    java.lang.String getValue();

    /**
     * <code>string Value = 3;</code>
     * 
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString getValueBytes();
}
