// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package scyna.proto;

public interface StartTaskResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:scyna.StartTaskResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 Id = 1;</code>
     * 
     * @return The id.
     */
    long getId();
}
